from __future__ import annotations

from typing import Final, Set


# Technische Begriffe und Systemkomponenten, die praktisch nie Orte sind
LOC_BAD_SYSTEM_TOKENS: Final[Set[str]] = {
    "account",
    "accounts",
    "admin",
    "administrator",
    "adminportal",
    "api",
    "app",
    "apps",
    "backend",
    "browser",
    "browsersession",
    "build",
    "cache",
    "channel",
    "channels",
    "client",
    "clients",
    "cluster",
    "codebase",
    "compliance",
    "config",
    "configuration",
    "konfiguration",
    "console",
    "crm",
    "dashboard",
    "dashboards",
    "database",
    "datenbank",
    "datenbanken",
    "db",
    "deployment",
    "deployments",
    "directory",
    "download",
    "downloads",
    "editor",
    "endpoint",
    "endpoints",
    "engine",
    "engines",
    "entrypoint",
    "entrypoints",
    "environment",
    "environments",
    "error",
    "errors",
    "export",
    "exports",
    "feed",
    "feeds",
    "file",
    "files",
    "filter",
    "filters",
    "flow",
    "flows",
    "frontend",
    "gateway",
    "gateways",
    "group",
    "groups",
    "helpdesk",
    "hook",
    "hooks",
    "import",
    "imports",
    "index",
    "instance",
    "instances",
    "integration",
    "integrationen",
    "job",
    "jobs",
    "komponente",
    "komponenten",
    "konsole",
    "landingpage",
    "layer",
    "layers",
    "log",
    "logging",
    "login",
    "logins",
    "logout",
    "logouts",
    "mailbox",
    "mapping",
    "mappings",
    "menu",
    "menü",
    "message",
    "messages",
    "messaging",
    "microservice",
    "microservices",
    "middleware",
    "modul",
    "module",
    "monitor",
    "monitoring",
    "node",
    "nodes",
    "notification",
    "notifications",
    "page",
    "pages",
    "panel",
    "panels",
    "pipeline",
    "pipelines",
    "plattform",
    "plattformen",
    "platform",
    "platforms",
    "portal",
    "portale",
    "process",
    "prozess",
    "prozesse",
    "profil",
    "profile",
    "profiles",
    "queue",
    "queues",
    "record",
    "records",
    "registry",
    "repo",
    "repos",
    "repository",
    "request",
    "requests",
    "resource",
    "resources",
    "response",
    "responses",
    "routing",
    "screen",
    "screens",
    "sdk",
    "search",
    "service",
    "services",
    "servicecenter",
    "session",
    "sessions",
    "server",
    "server01",
    "server02",
    "server03",
    "setup",
    "snippet",
    "snippets",
    "software",
    "source",
    "sources",
    "stack",
    "staging",
    "status",
    "storage",
    "stream",
    "streams",
    "support",
    "sync",
    "system",
    "systeme",
    "tab",
    "tabs",
    "task",
    "tasks",
    "template",
    "templates",
    "terminal",
    "ticket",
    "tickets",
    "tool",
    "tools",
    "tracker",
    "ui",
    "upload",
    "uploads",
    "user",
    "users",
    "ux",
    "variable",
    "variablen",
    "vault",
    "version",
    "versionen",
    "viewer",
    "view",
    "views",
    "webhook",
    "webhooks",
    "widget",
    "widgets",
    "window",
    "windows",
    "workflow",
    "workflows",
    "workspace",
    "workspaces",
}


# Kommunikations- und Kontaktmarker
LOC_BAD_CONTACT_TOKENS: Final[Set[str]] = {
    "fax",
    "mail",
    "telefon",
    "telefonnummer",
    "tel",
    "kontaktformular",
    "signatur",
}


# Allgemeine Sach- und Verwaltungsbegriffe, die keine Orte sind
LOC_BAD_GENERIC_TOKENS: Final[Set[str]] = {
    "auftrag",
    "aufträge",
    "bestellung",
    "bestellungen",
    "bestellnummer",
    "bestellnummern",
    "bereich",
    "bereiche",
    "beispiel",
    "event",
    "events",
    "kundencenter",
    "kundenbereich",
    "kundennummer",
    "kundennummern",
    "management",
    "manager",
    "nummer",
    "nummern",
    "option",
    "optionen",
    "order",
    "orders",
    "projekt",
    "projekte",
    "projektid",
    "projekt-id",
    "seite",
    "seiten",
    "statistik",
}


# Fachliche Begriffe, die in Verträgen / Tickets / Beschreibungen vorkommen,
# aber keine Orte bezeichnen
LOC_BAD_DOMAIN_TOKENS: Final[Set[str]] = {
    "flur",
    "ladenfläche",
    "ladenflaeche",
    "monatskaltmieten",
    "patientenportal",
    "waschraum",
    "waschraums",
}


# Sehr kurze Tokens oder Abkürzungen, die praktisch nie Orte sind
LOC_BAD_SHORT_TOKENS: Final[Set[str]] = {
    "tel",
    "fax",
    "mob",
    "fon",
    "nr",
    "no",
    "id",
    "ref",
    "url",
    "uid",
    "api",
    "ui",
    "ip",
    "db",
    "vm",
    "os",
    "hr",
    "it",
    "qa",
    "pm",
}


TECHNICAL_LOC_BLACKLIST: Final[Set[str]] = (
    LOC_BAD_SYSTEM_TOKENS
    | LOC_BAD_CONTACT_TOKENS
    | LOC_BAD_GENERIC_TOKENS
    | LOC_BAD_DOMAIN_TOKENS
    | LOC_BAD_SHORT_TOKENS
)