from __future__ import annotations

from typing import Final, Set


ORG_LEGAL_SUFFIXES: Final[Set[str]] = {
    "AG",
    "GmbH",
    "SE",
    "KG",
    "KGaA",
    "mbH",
    "UG",
    "e.V.",
    "Inc",
    "Corp",
    "Corporation",
    "Ltd",
    "LLC",
}


# Eindeutig formale Dokument- und Überschriftenbegriffe.
# Diese sind als alleinstehende ORG-Spans praktisch nie sinnvoll.
ORG_BAD_DOCUMENT_TOKENS: Final[Set[str]] = {
    "absatz",
    "akte",
    "aktenzeichen",
    "anhang",
    "anlage",
    "antrag",
    "artikel",
    "auszug",
    "bemerkung",
    "bescheid",
    "beschreibung",
    "bezeichnung",
    "dokument",
    "dokumentation",
    "dokumenttyp",
    "eintrag",
    "ergänzung",
    "ergaenzung",
    "erklärung",
    "erklaerung",
    "formular",
    "hinweis",
    "inhalt",
    "kapitel",
    "kategorie",
    "kommentar",
    "mitteilung",
    "nachtrag",
    "notiz",
    "nummer",
    "paragraph",
    "punkt",
    "referenz",
    "rubrik",
    "satz",
    "schreiben",
    "seite",
    "sektion",
    "signatur",
    "spalte",
    "struktur",
    "text",
    "thema",
    "titel",
    "unterlage",
    "unterlagen",
    "vermerk",
    "version",
    "vorlage",
    "vorgang",
    "vorgangsnummer",
    "zusammenfassung",
    "zusatz",
    "satzung",
    "richtlinie",
    "ordnung",
    "verordnung",
    "leitlinie",
    "leitfaden",
    "protokoll",
    "sitzungsprotokoll",
    "besprechungsprotokoll",
    "bericht",
    "gutachten",
    "bescheinigung",
    "bestätigung",
    "bestaetigung",
    "nachweis",
    "angebot",
    "rechnung",
    "kündigung",
    "kuendigung",
    "vertrag",
    "arbeitsvertrag",
    "mietvertrag",
    "gewerbemietvertrag",
    "kaufvertrag",
    "liefervertrag",
    "dienstvertrag",
    "werkvertrag",
    "rahmenvertrag",
    "leasingvertrag",
    "darlehensvertrag",
    "lizenzvertrag",
    "nutzungsvertrag",
    "kooperationsvertrag",
    "partnerschaftsvertrag",
    "gesellschaftsvertrag",
    "beratungsvertrag",
}


# Eindeutig technische / UI-nahe Einzelbegriffe.
# Bewusst klein gehalten, damit legitime Firmennamen nicht weggedrückt werden.
ORG_BAD_SYSTEM_TOKENS: Final[Set[str]] = {
    "admin",
    "api",
    "auth",
    "backend",
    "browser",
    "client",
    "code",
    "dashboard",
    "datenbank",
    "endpoint",
    "export",
    "fehler",
    "frontend",
    "host",
    "http",
    "https",
    "login",
    "logout",
    "menü",
    "menu",
    "monitoring",
    "navigation",
    "netzwerk",
    "node",
    "pdf",
    "queue",
    "screen",
    "sdk",
    "session",
    "setup",
    "status",
    "task",
    "token",
    "ui",
    "url",
    "user",
    "username",
    "vpn",
    "webapp",
    "webseite",
    "website",
    "workflow",
}


# Kommunikations- und Metabegriffe.
# Ebenfalls nur Begriffe, die als ORG allein praktisch nie korrekt sind.
ORG_BAD_COMMUNICATION_TOKENS: Final[Set[str]] = {
    "channel",
    "chat",
    "e-mail",
    "email",
    "fax",
    "kontakt",
    "kontaktperson",
    "mail",
    "message",
    "nachricht",
    "reply",
    "sms",
    "teams",
    "telefon",
    "telefonnummer",
    "thread",
}


# Klar generische Sachbegriffe.
# Keine typischen echten Unternehmensbestandteile aufnehmen.
ORG_BAD_GENERIC_TOKENS: Final[Set[str]] = {
    "adresse",
    "anschrift",
    "arbeitgeber",
    "arbeitnehmer",
    "arbeitnehmerin",
    "besitz",
    "betrag",
    "datum",
    "eigentum",
    "gefahr",
    "gehalt",
    "iban",
    "konto",
    "kaufpreis",
    "kunde",
    "kundin",
    "leiter",
    "leiterin",
    "mitarbeiter",
    "mitarbeiterin",
    "personal",
    "personalnummer",
    "position",
    "prüfung",
    "pruefung",
    "recht",
    "schriftform",
    "standort",
    "strasse",
    "straße",
    "zahlung",
    "zeitpunkt",
}


# Gängige Kennzeichner / Abkürzungen / IDs.
# Diese tauchen oft in technischen oder organisatorischen Texten auf,
# sind aber praktisch nie valide Organisationen.
ORG_BAD_ABBREVIATION_TOKENS: Final[Set[str]] = {
    "id",
    "projekt-id",
    "ticket-id",
    "case-id",
    "doc-id",
    "user-id",
    "order-id",
    "req-id",
    "ref-id",
    "obj-id",
    "kundennummer",
    "kundennr",
    "kunden-nr",
    "vorgangsnummer",
    "vorgangsnr",
    "vorgangsnr",
    "aktenzeichen",
    "personalnummer",
    "personalnr",
    "mitarbeiternummer",
    "mitarbeiternr",
    "ticketnummer",
    "ticketnr",
    "projektnummer",
    "projektnr",
    "referenznummer",
    "referenznr",
    "belegnummer",
    "belegnr",
    "vertragsnummer",
    "vertragsnr",
    "rechnungsnummer",
    "rechnungsnr",
    "bestellnummer",
    "bestellnr",
    "seriennummer",
    "seriennr",
    "artikelnummer",
    "artikelnr",
}


# Sehr kurze Artefakte.
ORG_BAD_SHORT_TOKENS: Final[Set[str]] = {
    "fw",
    "mb",
    "ok",
    "ui",
}


ORG_BAD_TOKENS: Final[Set[str]] = (
    ORG_BAD_DOCUMENT_TOKENS
    | ORG_BAD_SYSTEM_TOKENS
    | ORG_BAD_COMMUNICATION_TOKENS
    | ORG_BAD_GENERIC_TOKENS
    | ORG_BAD_ABBREVIATION_TOKENS
    | ORG_BAD_SHORT_TOKENS
)